version: '3.8'

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: shop-nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony_ase-new:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    depends_on:
      - shop-back
      - shop-mysql

  shop-back:
    build:
      context: ./symfony_ase-new
      dockerfile: Dockerfile
    container_name: shop-back
    volumes:
      - ./symfony_ase-new:/var/www/project
    networks:
      - my-network
    depends_on:
      - shop-mysql

  shop-mysql:
    image: mysql:8.0.32
    container_name: shop-mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network

  shop-front:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    container_name: shop-front
    volumes:
      - ./vue-project:/var/www/shop-front
    ports:
      - "5173:5173"
    networks:
      - my-network

  shop-elastic:
    image: elasticsearch:8.16.5
    container_name: shop-elastic
    environment:
      - discovery.type=single-node
      - node.name=shop-elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:  # Название тома, используемого MySQL
